@baseUrl = http://localhost:8000/users

###
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "name":"kamalesh",
    "email":"kamAlesh0122@gmail.com",
    "phone":"+919179401840",
    "password":"Kamalesh"
}

###
POST {{baseUrl}}/signin
Content-Type: application/json

{
    "email":"kamalesh0122@gmail.com",
    "password":"Kamalesh"
}

###
POST {{baseUrl}}/resetPassword
Content-Type: application/json

{
    "email":"kamalesh0122@gmail.com"
}